openapi: 3.0.0
info:
  title: Swagger Apis
  description: This is a sample server Mock server. You can find response of some api at here
  contact:
    email: protagonisths@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: "http://swagger.io"
servers:
  - url: /mock-api/v1
tags:
  - name: user
    description: about user apis
paths:
  /user:
    get:
      tags:
        - user
      summary: get users data
      description: return users data
      operationId: getUsers
      security:
        - AccessTokenAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                err:
                  type: integer
                  format: int64
                users:
                  type: object
